#####################################################################
# Each new term in the Fibonacci sequence is generated by           #
# adding the previous two terms. By starting with 1 and 2,          #
# the first 10 terms will be:                                       #
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...                            #
#                                                                   #
# By considering the terms in the Fibonacci sequence whose          #
# values do not exceed four million, find the sum of the            #
# even-valued terms.                                                #
#####################################################################

class Fibonacci

    def fibonacci(limit)
        array = [1,2]
        sum = 0
        until (array[-1] + array[-2]) > limit 
        # array.last + array[array.length - 2]
            number = array[-1] + array[-2]
            array.push(number)
            if array[-1] % 2 == 0 # array.last.even?
                sum += array[-1]
            end
        end
        puts sum
    end


end

evenFibonacci = Fibonacci.new
evenFibonacci.fibonacci(4000000)